spring.application.name=Flex-Gym-Management-System-Backend
spring.datasource.url=jdbc:mysql://localhost:3306/flex_gym_management_system?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true