spring.application.name=Flex-Gym-Management-System-Backend
spring.datasource.url=jdbc:mysql://localhost:3306/flex_gym_management_system?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# mail sender configuration
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=wggachathungabimsara2007@gmail.com
spring.mail.password=rbnc bcqa omux gdcd
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true